import time 
num1 = input('Enter first number:')
num2 = input('Enter second number:')
num3 = input('Enter third number:')
time.sleep(2)
print('Calculating')
time.sleep(3)
times = float(num1) * float(num2)
ans = float(times) - float(num3)
print(ans)
